# Copyright (c) 2021-2026 Tilmann Unte, Antonia Geßwein
# SPDX-License-Identifier:  Apache-2.0

### Scheduling and OS specific
# Deactivate boot message if your really hard pressed for memory
CONFIG_BOOT_BANNER=n

# High-frequency tick-rate, to meet our timing precision requirements
CONFIG_SYS_CLOCK_TICKS_PER_SEC=100000

# We use fine-grained pre-emptive priorities
CONFIG_NUM_PREEMPT_PRIORITIES=127

# This scheduler uses red-black trees and has high codesize, but good scalability
CONFIG_SCHED_SCALABLE=y
# Activates support for relative deadlines, arbitration only within the same priority!
CONFIG_SCHED_DEADLINE=y

# Activate Sensor subsystem (required for pretty much everything in this project)
CONFIG_SENSOR=y

# Uncomment/Activate the following to use Queue(1) deadline miss handling strategy (default: Skip-Next)
CONFIG_RPLIDAR_DEADLINE_MISS_STRATEGY_QUEUE=y

### Logging
# Reroute Zephyr serial console to specific UART!
CONFIG_CONSOLE=y
CONFIG_CONSOLE_HANDLER=n
#CONFIG_UART_CONSOLE=y

# Activate Logging
#CONFIG_LOG_BUFFER_SIZE=4096
#CONFIG_LOG=y
#CONFIG_LOG_MODE_DEFERRED=y # Warning: this converts printk to logging messages, but this is generally prefered to not slow down application threads
##CONFIG_LOG_MODE_IMMEDIATE=n # in conflict with DEFERRED, but may be useful sometimes
#CONFIG_LOG_PROCESS_THREAD=y
## Speed up log message handling at the cost of memory footprint
#CONFIG_LOG_SPEED=y
# ERR&WRN&INF&DBG=4, ERR&WRN&INF=3, ERR&WRN=2, ERR=1, (None)=0
#CONFIG_LOG_MAX_LEVEL=3

### Debugging (may depend on logging!)
# Build system will warn about assert, but it is useful for critical errors!
#CONFIG_ASSERT=y

# Turns off compiler optimizations (WARNING: this will massively increase required stack sizes, especially if combined with logging)
CONFIG_NO_OPTIMIZATIONS=y

# allows for thread-awareness in GDB sessions
#CONFIG_DEBUG_THREAD_INFO=y

# allows for worst case stack usage analysis (e.g. using puncover)
#CONFIG_STACK_USAGE=y

# Tracing, will cause delays and probably break real-time applications
#CONFIG_TRACING=y
#CONFIG_TRACING_CTF=y
#CONFIG_TRACING_BACKEND_RAM=y
#CONFIG_RAM_TRACING_BUFFER_SIZE=16384

# Collects data on thread execution, less likely to break application (report triggered by ur_magni_system thread every minute)
#CONFIG_THREAD_NAME=y
#CONFIG_THREAD_ANALYZER=y
#CONFIG_THREAD_ANALYZER_AUTO_SEPARATE_CORES=n
#CONFIG_THREAD_ANALYZER_USE_LOG=y

# Produces a coredump for use in GDB whenever the system crashes
#CONFIG_DEBUG_COREDUMP=y
#CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=y

#CONFIG_INIT_STACKS=y
#CONFIG_THREAD_STACK_INFO=y
#CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=16384

CONFIG_TIMING_FUNCTIONS=y
#CONFIG_MINIMAL_LIBC=y
