# Copyright (c) 2025-2026 Tilmann Unte, Antonia Geßwein
# SPDX-License-Identifier:  Apache-2.0

# Activate UART serial connection (Debug, Magni, RPLIDAR)
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

#CONFIG_SRAM_VECTOR_TABLE=y
#CONFIG_SRAM_SW_ISR_TABLE=y

# Overflow protection
#CONFIG_HW_STACK_PROTECTION=y

CONFIG_FPU=y

################################################################################
# Include Slamtech RPLidar Driver
CONFIG_RPLIDAR=y
